// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using client_contact_management.Data;

#nullable disable

namespace client_contact_management.Migrations
{
    [DbContext(typeof(ClientContactManagementDbContext))]
    [Migration("20260312075612_AddedCascadeDelete")]
    partial class AddedCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("client_contact_management.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_ClientCode")
                        .HasFilter("[ClientCode] IS NOT NULL");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Clients_Name");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("client_contact_management.Entities.ClientContact", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "ContactId");

                    b.HasIndex("ContactId", "ClientId")
                        .HasDatabaseName("IX_ClientContacts_ContactId_ClientId");

                    b.ToTable("ClientContacts");
                });

            modelBuilder.Entity("client_contact_management.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Contacts_Email");

                    b.HasIndex("Surname", "Name")
                        .HasDatabaseName("IX_Contacts_Surname_Name");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("client_contact_management.Entities.ClientContact", b =>
                {
                    b.HasOne("client_contact_management.Entities.Client", "Client")
                        .WithMany("ClientContacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("client_contact_management.Entities.Contact", "Contact")
                        .WithMany("ClientContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("client_contact_management.Entities.Client", b =>
                {
                    b.Navigation("ClientContacts");
                });

            modelBuilder.Entity("client_contact_management.Entities.Contact", b =>
                {
                    b.Navigation("ClientContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
